### ISSUE TITLE
How to generate the dataset used in paper?

### ISSUE THREAD

**Issue by Tangent-Wei** [amirhertz/visual_motif_removal#3]

**Comment by lukemelas** [comment]
Just following up on this. It would be wonderful to get some more detailed instructions for constructing the paper dataset!

**Comment by zhaoxin111** [comment]
run cache_utils.py, the code is very nice!

**Comment by phper5** [comment]
should I train the gray scale texts, colored texts,  emojis and  geometric grayscale shapes in one train or four?
however in my train ,the loss not decrease while it read 1.x
